-- V1 modelo mínimo (SQLite). Fechas TEXT YYYY-MM-DD, intervalo [llegada,salida).
CREATE TABLE IF NOT EXISTS hotel_config(clave TEXT PRIMARY KEY, valor TEXT);
CREATE TABLE IF NOT EXISTS room_types(id INTEGER PRIMARY KEY AUTOINCREMENT, codigo TEXT UNIQUE NOT NULL, nombre TEXT NOT NULL, capacidad_max INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rooms(id INTEGER PRIMARY KEY AUTOINCREMENT, codigo TEXT UNIQUE NOT NULL, room_type_id INTEGER NOT NULL REFERENCES room_types(id), estado TEXT NOT NULL DEFAULT 'ACTIVA');
CREATE TABLE IF NOT EXISTS reservations(id INTEGER PRIMARY KEY AUTOINCREMENT, codigo TEXT UNIQUE NOT NULL, email TEXT NOT NULL, llegada TEXT NOT NULL, salida TEXT NOT NULL, huespedes INTEGER NOT NULL, estado TEXT NOT NULL, origen TEXT NOT NULL, idempotencia TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS reservation_items(id INTEGER PRIMARY KEY AUTOINCREMENT, reservation_id INTEGER NOT NULL REFERENCES reservations(id), room_id INTEGER NOT NULL REFERENCES rooms(id), desde TEXT NOT NULL, hasta TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS blocks(id INTEGER PRIMARY KEY AUTOINCREMENT, room_id INTEGER REFERENCES rooms(id), desde TEXT NOT NULL, hasta TEXT NOT NULL, motivo TEXT);
-- DEMO: sin datos reales. Semillas solo en desarrollo y marcadas DEMO (Ronda 2).
